### PR TITLE
(#88) Add instance name replacement of destination

### LINKED ISSUE #88: Request: Ability to specify instance name in download paths
## :frowning_person: Problem Statement

When I am running multiple test scenarios, I would like each instance to output to it's own path.

## :grey_question: Possible Solution

I see in the documentation for kitchen-vagrant that there is `%{instance_name}` that they use to insert the instance name. Using something similar for output Pester results would be beneficial.

## :arrow_heading_up: Describe alternatives you've considered

I've tried `%{instance_name}` and `{{vagrant_root}}` as ways to try and get a unique path. Unfortunately it looks like these are both provider specific and not expanded by Test Kitchen.

## :heavy_plus_sign: Additional context

It looks like `kitchen-vagrant` does a simple search and replace: https://github.com/test-kitchen/kitchen-vagrant/blob/cfd1366244a85736f837b326b9d5d760ff7786c7/lib/kitchen/driver/vagrant.rb#L336 I would suggest `kitchen-pester` take a similar approach to keep is semi-consistent.

### PR DESCRIPTION
**Pull request by corbob**
# Description

Replaces `%{instance_name} in the destination with the instance name.

## Issues Resolved

Fixes #88 

## Check List

- [x] All tests pass. See TESTING.md for details.
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by corbob** [comment]
@vexx32 assuming I understand what you were asking, I think I've got this setup. I don't actually see any Azure Pipelines runs on the PR itself, so I'm not sure how to verify it.

**Comment by vexx32** [comment]
Thanks! There is a run that happens, but I think something's up with our test config here. Not familiar with the implementation but it definitely looks like it simply isn't running the tests properly under the Windows Integration test task. Might have to reach out to Steve to ask about that, I'll file an issue and we'll follow up on that a bit later.

**Review by vexx32 — APPROVED** [review]
Looks good to me, thanks for the PR!

**Comment by vexx32** [comment]
🤔 not sure what those lint checks are, those are new. @tas50 are those something we need to setup for this repository? Can I copy the task definitions for those from another test-kitchen repo?

**Pull request merged**
